### ISSUE TITLE
proxiedNet.connect doesn't actually connect

### ISSUE THREAD

**Issue by aeroxy** [krisives/proxysocket#15]
```
var proxysocket = require('proxysocket');
var net = proxysocket.create('localhost', 8889); // charles socks5

console.log('Connecting');
var remote = net.connect(80, 'www.google.com', () => {
  console.log('Connected');
});
```

Result:

1. Console shows 'Connecting'.
2. Charles received nothing.
3. No Connected printed.

**Comment by aeroxy** [comment]
It looks like the other npm package `socks` works just fine.

**Comment by krisives** [comment]
Sorry this project has not been maintained and was written a long time ago and Nodejs has changed a lot over time. If you want to submit a PR that says it's outdated in the README.md I will merge it.

**Comment by samuel-crypto** [comment]
@krisives @aeroxy This issue has intrigued me and I was wondering if I could chime in and see what I can do on a PR of this kind? I think @aeroxy came up with the issue so it is your call whether you want to do it or leave it to me

**Comment by krisives** [comment]
Anyone can do it and I will merge the PR.
